import type { Localized, RawCourse } from "./types";

/** MOCK DATA — invented course programs for development. Slugs are final-form English. */

const L = (uz: string, ru: string, en: string): Localized => ({ uz, ru, en });

export const mockCourses: RawCourse[] = [
  {
    id: "c-office",
    slug: "office-it-foundation",
    category: "office",
    title: L("Office / IT Foundation", "Office / IT Foundation", "Office / IT Foundation"),
    summary: L(
      "Kompyuter savodxonligi va amaliy dasturlar bilan ishonchli ishlash.",
      "Компьютерная грамотность и уверенная работа с прикладными программами.",
      "Computer literacy and confident work with everyday productivity tools.",
    ),
    description: L(
      "Kompyuter bilan endi tanishayotganlar va ish joyida tezroq ishlashni istaganlar uchun kurs. Hujjat, jadval va taqdimotlarni tayyorlashni, internet va elektron pochtadan xavfsiz foydalanishni amaliy topshiriqlar orqali o‘rganasiz.",
      "Курс для тех, кто только знакомится с компьютером или хочет работать быстрее. На практических заданиях вы научитесь готовить документы, таблицы и презентации, безопасно пользоваться интернетом и почтой.",
      "For people new to computers or anyone who wants to work faster. Through hands-on tasks you learn to prepare documents, spreadsheets and presentations, and to use the internet and email safely.",
    ),
    durationMonths: 2,
    lessonsPerWeek: 3,
    level: "beginner",
    format: "offline",
    branchIds: ["tashkent", "samarkand", "andijan"],
    modules: [
      L("Kompyuter va operatsion tizim asoslari", "Основы компьютера и операционной системы", "Computer and operating system basics"),
      L("Word: hujjatlar va rasmiylashtirish", "Word: документы и оформление", "Word: documents and formatting"),
      L("Excel: jadvallar, formulalar, diagrammalar", "Excel: таблицы, формулы, диаграммы", "Excel: tables, formulas, charts"),
      L("PowerPoint: taqdimotlar", "PowerPoint: презентации", "PowerPoint: presentations"),
      L("Internet, pochta va raqamli xavfsizlik", "Интернет, почта и цифровая безопасность", "Internet, email and digital safety"),
    ],
    outcomes: [
      L("Ish hujjatlarini mustaqil tayyorlaysiz", "Самостоятельно готовите рабочие документы", "Prepare work documents on your own"),
      L("Excel'da hisob-kitob va hisobot qilasiz", "Считаете и строите отчёты в Excel", "Do calculations and reports in Excel"),
      L("Onlayn xizmatlardan xavfsiz foydalanasiz", "Безопасно пользуетесь онлайн-сервисами", "Use online services safely"),
    ],
  },
  {
    id: "c-design",
    slug: "graphic-design",
    category: "design",
    title: L("Grafik dizayn", "Графический дизайн", "Graphic Design"),
    summary: L(
      "Ijodiy va texnologik ko‘nikmalarni rivojlantiruvchi dastur.",
      "Программа, развивающая творческие и технические навыки.",
      "A program that builds creative and technical skills together.",
    ),
    description: L(
      "Kompozitsiya, rang va tipografiyadan boshlab brend identifikatsiyasigacha. Figma va Adobe dasturlarida real buyurtmalarga o‘xshash topshiriqlar bajarib, kurs oxirida portfolio yig‘asiz.",
      "От композиции, цвета и типографики до айдентики бренда. Вы выполняете задания, похожие на реальные заказы, в Figma и программах Adobe и к концу курса собираете портфолио.",
      "From composition, color and typography to brand identity. You work on client-style briefs in Figma and Adobe tools and finish the course with a portfolio.",
    ),
    durationMonths: 5,
    lessonsPerWeek: 3,
    level: "beginner",
    format: "hybrid",
    branchIds: ["tashkent", "samarkand"],
    modules: [
      L("Kompozitsiya va rang nazariyasi", "Композиция и теория цвета", "Composition and color theory"),
      L("Tipografiya", "Типографика", "Typography"),
      L("Adobe Photoshop va Illustrator", "Adobe Photoshop и Illustrator", "Adobe Photoshop and Illustrator"),
      L("Figma va ijtimoiy tarmoq dizayni", "Figma и дизайн для соцсетей", "Figma and social media design"),
      L("Logotip va brend identifikatsiyasi", "Логотип и айдентика бренда", "Logo and brand identity"),
      L("Portfolio va buyurtmachi bilan ishlash", "Портфолио и работа с заказчиком", "Portfolio and working with clients"),
    ],
    outcomes: [
      L("6–8 ishdan iborat portfolio", "Портфолио из 6–8 работ", "A portfolio of 6–8 pieces"),
      L("Brend uchun to‘liq vizual uslub yaratasiz", "Создаёте полный визуальный стиль бренда", "Create a complete visual style for a brand"),
      L("Frilans buyurtmalarni olishga tayyorsiz", "Готовы брать фриланс-заказы", "Ready to take freelance orders"),
    ],
  },
  {
    id: "c-frontend",
    slug: "frontend-development",
    category: "programming",
    title: L("Frontend dasturlash", "Frontend-разработка", "Frontend Development"),
    summary: L(
      "HTML, CSS, JavaScript va React bilan real loyihalar yaratish.",
      "Создание реальных проектов на HTML, CSS, JavaScript и React.",
      "Build real projects with HTML, CSS, JavaScript and React.",
    ),
    description: L(
      "Veb-sahifa tuzilishidan zamonaviy React ilovalarigacha. Har modul loyiha bilan tugaydi, kod mentor tomonidan tekshiriladi, Git va jamoaviy ish odatlari birinchi haftadan boshlanadi.",
      "От структуры веб-страницы до современных React-приложений. Каждый модуль заканчивается проектом, код проверяет ментор, Git и командная работа — с первой недели.",
      "From web page structure to modern React apps. Every module ends with a project, a mentor reviews your code, and Git and teamwork habits start in week one.",
    ),
    durationMonths: 8,
    lessonsPerWeek: 3,
    level: "intermediate",
    format: "offline",
    branchIds: ["tashkent", "andijan"],
    modules: [
      L("HTML va semantik belgilash", "HTML и семантическая разметка", "HTML and semantic markup"),
      L("CSS, Flexbox, Grid va moslashuvchan dizayn", "CSS, Flexbox, Grid и адаптивная вёрстка", "CSS, Flexbox, Grid and responsive layout"),
      L("JavaScript asoslari va DOM", "Основы JavaScript и DOM", "JavaScript fundamentals and the DOM"),
      L("Asinxron JavaScript va API bilan ishlash", "Асинхронный JavaScript и работа с API", "Async JavaScript and working with APIs"),
      L("Git va GitHub", "Git и GitHub", "Git and GitHub"),
      L("React: komponentlar, holat, marshrutlash", "React: компоненты, состояние, маршрутизация", "React: components, state, routing"),
      L("Diplom loyihasi", "Дипломный проект", "Capstone project"),
    ],
    outcomes: [
      L("GitHub'da 5+ loyiha", "5+ проектов на GitHub", "5+ projects on GitHub"),
      L("Junior frontend lavozimiga intervyuga tayyorsiz", "Готовы к собеседованию на junior frontend", "Ready for junior frontend interviews"),
      L("Jamoada Git bilan ishlay olasiz", "Умеете работать с Git в команде", "Work with Git in a team"),
    ],
  },
  {
    id: "c-python",
    slug: "python-backend",
    category: "programming",
    title: L("Python va backend", "Python и backend", "Python & Backend"),
    summary: L(
      "Python, ma’lumotlar bazasi va API yaratish asoslaridan boshlab.",
      "От основ Python до баз данных и создания API.",
      "From Python basics to databases and building APIs.",
    ),
    description: L(
      "Dasturlashni noldan boshlab, server tomonini o‘rganasiz: Python, SQL, ma’lumotlar bazasi, REST API va deploy. Kurs oxirida o‘z backend xizmatingizni internetga chiqarasiz.",
      "Начинаете программировать с нуля и изучаете серверную часть: Python, SQL, базы данных, REST API и деплой. К концу курса выкладываете свой backend-сервис в интернет.",
      "Start programming from zero and learn the server side: Python, SQL, databases, REST APIs and deployment. By the end you put your own backend service online.",
    ),
    durationMonths: 8,
    lessonsPerWeek: 3,
    level: "intermediate",
    format: "offline",
    branchIds: ["tashkent"],
    modules: [
      L("Python asoslari", "Основы Python", "Python fundamentals"),
      L("OOP va modullar", "ООП и модули", "OOP and modules"),
      L("SQL va PostgreSQL", "SQL и PostgreSQL", "SQL and PostgreSQL"),
      L("Django / FastAPI bilan REST API", "REST API на Django / FastAPI", "REST APIs with Django / FastAPI"),
      L("Autentifikatsiya va xavfsizlik", "Аутентификация и безопасность", "Authentication and security"),
      L("Docker va deploy", "Docker и деплой", "Docker and deployment"),
    ],
    outcomes: [
      L("Ishlaydigan REST API loyihasi", "Рабочий REST API-проект", "A working REST API project"),
      L("Ma’lumotlar bazasini loyihalay olasiz", "Умеете проектировать базы данных", "Design databases"),
      L("Junior backend intervyusiga tayyorsiz", "Готовы к собеседованию на junior backend", "Ready for junior backend interviews"),
    ],
  },
  {
    id: "c-smm",
    slug: "smm-marketing",
    category: "marketing",
    title: L("SMM va marketing", "SMM и маркетинг", "SMM & Marketing"),
    summary: L(
      "Kontent, reklama va tahlil: brendni ijtimoiy tarmoqlarda o‘stirish.",
      "Контент, реклама и аналитика: развитие бренда в соцсетях.",
      "Content, ads and analytics: growing a brand on social media.",
    ),
    description: L(
      "Instagram, Telegram va TikTok'da brend yuritishni o‘rganasiz: kontent-reja, vizual, target reklama va natijalarni o‘lchash. Kurs davomida haqiqiy sahifani boshqarasiz.",
      "Учитесь вести бренд в Instagram, Telegram и TikTok: контент-план, визуал, таргетированная реклама и измерение результатов. Во время курса ведёте настоящую страницу.",
      "Learn to run a brand on Instagram, Telegram and TikTok: content plans, visuals, targeted ads and measuring results. You manage a real page during the course.",
    ),
    durationMonths: 4,
    lessonsPerWeek: 2,
    level: "beginner",
    format: "hybrid",
    branchIds: ["samarkand", "andijan"],
    modules: [
      L("Marketing asoslari va auditoriya", "Основы маркетинга и аудитория", "Marketing basics and audience"),
      L("Kontent-reja va kopirayting", "Контент-план и копирайтинг", "Content plans and copywriting"),
      L("Mobil foto va video", "Мобильное фото и видео", "Mobile photo and video"),
      L("Target reklama", "Таргетированная реклама", "Targeted advertising"),
      L("Tahlil va hisobot", "Аналитика и отчётность", "Analytics and reporting"),
    ],
    outcomes: [
      L("Brend uchun 1 oylik kontent-reja", "Контент-план бренда на месяц", "A one-month content plan for a brand"),
      L("Reklama kampaniyasini ishga tushirasiz", "Запускаете рекламную кампанию", "Launch an ad campaign"),
      L("SMM-mutaxassis sifatida ishlashga tayyorsiz", "Готовы работать SMM-специалистом", "Ready to work as an SMM specialist"),
    ],
  },
];
