import type { RawPost } from "./types";

/** MOCK DATA — invented blog posts for development. Slugs are final-form English. */

export const mockPosts: RawPost[] = [
  {
    id: "p1",
    slug: "where-to-start-frontend",
    category: "guides",
    courseSlug: "frontend-development",
    publishedAt: "2026-09-08T09:00:00+05:00",
    author: { name: "Mentor A.", role: { uz: "Frontend mentori", ru: "Ментор по Frontend", en: "Frontend mentor" } },
    title: {
      uz: "Frontend'ni qayerdan boshlash kerak: 2026-yil uchun aniq reja",
      ru: "С чего начать frontend: понятный план на 2026 год",
      en: "Where to start with frontend: a clear plan for 2026",
    },
    excerpt: {
      uz: "Nimani, qaysi tartibda va qancha vaqt o‘rganish kerakligi — ortiqcha kurs va video dengizida adashmaslik uchun.",
      ru: "Что учить, в каком порядке и сколько времени — чтобы не утонуть в море курсов и видео.",
      en: "What to learn, in what order and for how long — so you don’t drown in courses and videos.",
    },
    body: {
      uz: [
        { type: "p", text: "Frontend — foydalanuvchi ko‘radigan va bosadigan hamma narsa. Yaxshi xabar: boshlash uchun kuchli kompyuter ham, matematika ham shart emas. Kerakli narsa — tartib va muntazamlik." },
        { type: "h2", text: "1. HTML va CSS: poydevor" },
        { type: "p", text: "Birinchi 4–6 haftani sahifa tuzilishi va dizaynga bering. Har kuni kichik bo‘lsa ham bitta sahifa yasang: vizitka, restoran menyusi, portfolio." },
        { type: "ul", items: ["Semantik teglar: header, main, section, article", "Flexbox va Grid", "Mobil ekranga moslashuv (responsive)"] },
        { type: "h2", text: "2. JavaScript: sahifani jonlantirish" },
        { type: "p", text: "O‘zgaruvchi, funksiya, massiv va obyektlardan so‘ng DOM bilan ishlashga o‘ting: tugma bosilganda nimadir o‘zgarsin. Keyin fetch bilan tashqi API'dan ma’lumot oling." },
        { type: "quote", text: "Video ko‘rish o‘rganish emas. Kod yozganingizdagina o‘rganasiz.", cite: "Mentor A." },
        { type: "h2", text: "3. Git va birinchi portfolio" },
        { type: "p", text: "Har bir mashqni GitHub'ga joylang. Ish beruvchi diplomdan ko‘ra ishlaydigan loyihalarga ko‘proq qaraydi." },
        { type: "h2", text: "4. React — oxirida, shoshilmasdan" },
        { type: "p", text: "JavaScript'ni ishonchli bilganingizdan keyingina React'ga o‘ting. Aks holda framework'ning sehrli ko‘ringan qismlari tushunarsiz qoladi." },
      ],
      ru: [
        { type: "p", text: "Frontend — это всё, что пользователь видит и нажимает. Хорошая новость: для старта не нужен мощный компьютер и математика. Нужны порядок и регулярность." },
        { type: "h2", text: "1. HTML и CSS: фундамент" },
        { type: "p", text: "Первые 4–6 недель посвятите структуре страницы и оформлению. Каждый день делайте хотя бы небольшую страницу: визитку, меню ресторана, портфолио." },
        { type: "ul", items: ["Семантические теги: header, main, section, article", "Flexbox и Grid", "Адаптация под мобильные экраны"] },
        { type: "h2", text: "2. JavaScript: оживляем страницу" },
        { type: "p", text: "После переменных, функций, массивов и объектов переходите к DOM: пусть по нажатию кнопки что-то меняется. Затем получайте данные из внешнего API через fetch." },
        { type: "quote", text: "Смотреть видео — не значит учиться. Учитесь, только когда пишете код.", cite: "Ментор A." },
        { type: "h2", text: "3. Git и первое портфолио" },
        { type: "p", text: "Выкладывайте каждое упражнение на GitHub. Работодатель смотрит на работающие проекты больше, чем на диплом." },
        { type: "h2", text: "4. React — в конце и без спешки" },
        { type: "p", text: "Переходите к React, только когда уверенно знаете JavaScript. Иначе «магические» части фреймворка останутся непонятными." },
      ],
      en: [
        { type: "p", text: "Frontend is everything a user sees and clicks. Good news: you don’t need a powerful computer or advanced math to start. You need order and consistency." },
        { type: "h2", text: "1. HTML and CSS: the foundation" },
        { type: "p", text: "Give the first 4–6 weeks to page structure and styling. Build at least one small page a day: a business card, a restaurant menu, a portfolio." },
        { type: "ul", items: ["Semantic tags: header, main, section, article", "Flexbox and Grid", "Responsive layouts for phones"] },
        { type: "h2", text: "2. JavaScript: bringing the page to life" },
        { type: "p", text: "After variables, functions, arrays and objects, move on to the DOM: make something change when a button is clicked. Then fetch data from an external API." },
        { type: "quote", text: "Watching videos isn’t learning. You learn only when you write code.", cite: "Mentor A." },
        { type: "h2", text: "3. Git and a first portfolio" },
        { type: "p", text: "Push every exercise to GitHub. Employers look at working projects more than at diplomas." },
        { type: "h2", text: "4. React — last, and without rushing" },
        { type: "p", text: "Move to React only once you’re confident in JavaScript. Otherwise the framework’s “magic” stays a mystery." },
      ],
    },
  },
  {
    id: "p2",
    slug: "first-robot-in-six-weeks",
    category: "stories",
    courseSlug: "robotics",
    publishedAt: "2026-08-27T10:00:00+05:00",
    author: { name: "Mentor C.", role: { uz: "Robototexnika mentori", ru: "Ментор по робототехнике", en: "Robotics mentor" } },
    title: {
      uz: "Olti haftada birinchi robot: guruhimiz tajribasi",
      ru: "Первый робот за шесть недель: опыт нашей группы",
      en: "A first robot in six weeks: our group’s story",
    },
    excerpt: {
      uz: "Hech qachon kavsharlagich ushlamagan o‘quvchilar qanday qilib chiziq bo‘ylab yuradigan robot yig‘ishdi.",
      ru: "Как ученики, ни разу не державшие паяльник, собрали робота, который едет по линии.",
      en: "How students who had never held a soldering iron built a line-following robot.",
    },
    body: {
      uz: [
        { type: "p", text: "Guruhimizda 12 kishi bor edi: eng kichigi 11 yosh, eng kattasi 17 yosh. Hech kim ilgari elektronika bilan shug‘ullanmagan." },
        { type: "h2", text: "Birinchi hafta: chiroqni yoqish" },
        { type: "p", text: "Arduino'ga LED ulab, uni miltillatish — oddiy ko‘rinadi, lekin aynan shu yerda o‘quvchilar kod va sim bir-biriga qanday bog‘lanishini birinchi marta ko‘rishadi." },
        { type: "h2", text: "To‘rtinchi hafta: sensorlar" },
        { type: "p", text: "Infraqizil sensor qora chiziqni oq poldan ajratadi. Shu bitta g‘oya robotning “ko‘zi” bo‘ladi." },
        { type: "quote", text: "Robot birinchi marta burilishdan to‘g‘ri o‘tganida butun xona qichqirib yubordi.", cite: "Mentor C." },
        { type: "h2", text: "Keyingi qadam" },
        { type: "p", text: "Endi guruh viloyat musobaqasiga tayyorlanyapti: robot tezroq va aniqroq yurishi kerak." },
      ],
      ru: [
        { type: "p", text: "В группе было 12 человек: младшему 11 лет, старшему 17. Никто раньше не занимался электроникой." },
        { type: "h2", text: "Первая неделя: зажечь светодиод" },
        { type: "p", text: "Подключить светодиод к Arduino и заставить его мигать — кажется простым, но именно здесь ученики впервые видят, как код и провода связаны друг с другом." },
        { type: "h2", text: "Четвёртая неделя: датчики" },
        { type: "p", text: "Инфракрасный датчик отличает чёрную линию от белого пола. Эта одна идея становится «глазами» робота." },
        { type: "quote", text: "Когда робот впервые правильно прошёл поворот, весь класс закричал.", cite: "Ментор C." },
        { type: "h2", text: "Что дальше" },
        { type: "p", text: "Теперь группа готовится к областным соревнованиям: робот должен ехать быстрее и точнее." },
      ],
      en: [
        { type: "p", text: "There were 12 people in the group: the youngest 11, the oldest 17. None had worked with electronics before." },
        { type: "h2", text: "Week one: light an LED" },
        { type: "p", text: "Wiring an LED to an Arduino and making it blink looks trivial, but it’s where students first see how code and wires connect." },
        { type: "h2", text: "Week four: sensors" },
        { type: "p", text: "An infrared sensor tells a black line from a white floor. That single idea becomes the robot’s “eyes”." },
        { type: "quote", text: "When the robot took its first corner correctly, the whole room shouted.", cite: "Mentor C." },
        { type: "h2", text: "What’s next" },
        { type: "p", text: "The group is now preparing for the regional competition: the robot has to go faster and more precisely." },
      ],
    },
  },
  {
    id: "p3",
    slug: "english-for-it",
    category: "guides",
    courseSlug: "english-a1-b2",
    publishedAt: "2026-08-14T09:00:00+05:00",
    author: { name: "Mentor D.", role: { uz: "Ingliz tili o‘qituvchisi", ru: "Преподаватель английского", en: "English teacher" } },
    title: {
      uz: "IT uchun ingliz tili: qaysi daraja yetarli?",
      ru: "Английский для IT: какого уровня достаточно?",
      en: "English for IT: what level is enough?",
    },
    excerpt: {
      uz: "Dasturchi uchun B1 ham ish beradi, lekin B2 eshiklarni ancha kengroq ochadi. Nega — tushuntiramiz.",
      ru: "Программисту подойдёт и B1, но B2 открывает гораздо больше дверей. Объясняем почему.",
      en: "B1 can work for a developer, but B2 opens many more doors. Here’s why.",
    },
    body: {
      uz: [
        { type: "p", text: "Dasturlashdagi eng yaxshi qo‘llanmalar, xatolar haqidagi javoblar va hujjatlar ingliz tilida. Shuning uchun til — bu ham texnik ko‘nikma." },
        { type: "h2", text: "A2–B1: hujjat o‘qish" },
        { type: "p", text: "Bu darajada texnik matnni lug‘at yordamida tushunasiz. Boshlash uchun yetarli, lekin sekin." },
        { type: "h2", text: "B2: jamoada ishlash" },
        { type: "p", text: "B2 bilan xalqaro jamoada gaplasha olasiz, intervyudan o‘tasiz va xorijiy buyurtmachi bilan yozishasiz." },
        { type: "ul", items: ["Har kuni 20 daqiqa texnik matn o‘qing", "Xato xabarlarini tarjima qilmasdan tushunishga harakat qiling", "Kod izohlarini ingliz tilida yozing"] },
      ],
      ru: [
        { type: "p", text: "Лучшие руководства, ответы на ошибки и документация в программировании — на английском. Поэтому язык — тоже технический навык." },
        { type: "h2", text: "A2–B1: чтение документации" },
        { type: "p", text: "На этом уровне вы понимаете технический текст со словарём. Для старта достаточно, но медленно." },
        { type: "h2", text: "B2: работа в команде" },
        { type: "p", text: "С B2 вы можете общаться в международной команде, проходить собеседования и переписываться с иностранным заказчиком." },
        { type: "ul", items: ["Читайте технический текст по 20 минут в день", "Старайтесь понимать сообщения об ошибках без перевода", "Пишите комментарии в коде на английском"] },
      ],
      en: [
        { type: "p", text: "The best tutorials, answers to errors and documentation in programming are in English. That makes language a technical skill too." },
        { type: "h2", text: "A2–B1: reading docs" },
        { type: "p", text: "At this level you understand technical text with a dictionary. Enough to start, but slow." },
        { type: "h2", text: "B2: working in a team" },
        { type: "p", text: "With B2 you can talk in an international team, pass interviews and correspond with foreign clients." },
        { type: "ul", items: ["Read technical text for 20 minutes a day", "Try to understand error messages without translating", "Write code comments in English"] },
      ],
    },
  },
  {
    id: "p4",
    slug: "free-masterclass-3d-printing",
    category: "events",
    courseSlug: "3d-printing",
    publishedAt: "2026-07-30T12:00:00+05:00",
    author: { name: "IT Shaharcha", role: { uz: "Jamoa", ru: "Команда", en: "Team" } },
    title: {
      uz: "Bepul mahorat darsi: 3D printerda birinchi buyum",
      ru: "Бесплатный мастер-класс: первая вещь на 3D-принтере",
      en: "Free masterclass: your first object on a 3D printer",
    },
    excerpt: {
      uz: "Bir soatda model chizamiz va uni bosib chiqaramiz. Oldindan tayyorgarlik shart emas.",
      ru: "За час нарисуем модель и напечатаем её. Подготовка не нужна.",
      en: "In one hour we’ll draw a model and print it. No preparation needed.",
    },
    body: {
      uz: [
        { type: "p", text: "Har oy 3D printer bo‘yicha ochiq dars o‘tkazamiz. Kim xohlasa qatnashishi mumkin — yosh va tajriba muhim emas." },
        { type: "h2", text: "Darsda nima qilamiz" },
        { type: "ul", items: ["Tinkercad'da oddiy brelok chizamiz", "Modelni printerga tayyorlaymiz", "Bosib chiqarishni jonli kuzatamiz"] },
        { type: "p", text: "Joylar soni cheklangan, shuning uchun oldindan ro‘yxatdan o‘ting." },
      ],
      ru: [
        { type: "p", text: "Каждый месяц мы проводим открытый урок по 3D-печати. Прийти может любой — возраст и опыт не важны." },
        { type: "h2", text: "Что будем делать" },
        { type: "ul", items: ["Нарисуем простой брелок в Tinkercad", "Подготовим модель к печати", "Вживую посмотрим на печать"] },
        { type: "p", text: "Количество мест ограничено, поэтому запишитесь заранее." },
      ],
      en: [
        { type: "p", text: "Every month we run an open lesson on 3D printing. Anyone can come — age and experience don’t matter." },
        { type: "h2", text: "What we’ll do" },
        { type: "ul", items: ["Draw a simple keychain in Tinkercad", "Prepare the model for printing", "Watch it print live"] },
        { type: "p", text: "Seats are limited, so sign up in advance." },
      ],
    },
  },
];
