import type { Localized, RawCourse } from "./types";

/**
 * MOCK DATA.
 * Real: ids and Uzbek titles, from the center's course list.
 * Invented: slugs (final-form English), ru/en titles, descriptions, durations,
 * schedules, modules, outcomes and branches — replace once the API provides them.
 */

const L = (uz: string, ru: string, en: string): Localized => ({ uz, ru, en });

const ALL = ["tashkent", "samarkand", "andijan"];

export const mockCourses: RawCourse[] = [
  {
    id: "1",
    slug: "programming-python-django",
    category: "programming",
    title: L(
      "Dasturlash kursi (Scratch, Python, PostgreSQL, Django)",
      "Курс программирования (Scratch, Python, PostgreSQL, Django)",
      "Programming (Scratch, Python, PostgreSQL, Django)",
    ),
    summary: L(
      "Scratch'dagi birinchi o‘yindan Django'dagi to‘liq veb-ilovagacha.",
      "От первой игры в Scratch до полноценного веб-приложения на Django.",
      "From a first game in Scratch to a full web app in Django.",
    ),
    description: L(
      "Dasturlashni noldan boshlaysiz: Scratch'da mantiqni vizual bloklar bilan tushunasiz, so‘ng Python, ma’lumotlar bazasi va Django bilan server tomonini o‘rganasiz. Kurs oxirida o‘z veb-ilovangizni internetga chiqarasiz.",
      "Начинаете с нуля: в Scratch понимаете логику на визуальных блоках, затем изучаете Python, базы данных и серверную часть на Django. К концу курса выкладываете своё веб-приложение в интернет.",
      "Start from zero: learn logic with visual blocks in Scratch, then Python, databases and the server side with Django. By the end you put your own web app online.",
    ),
    durationMonths: 9,
    lessonsPerWeek: 3,
    level: "beginner",
    format: "offline",
    branchIds: ALL,
    modules: [
      L("Scratch: algoritm va mantiq", "Scratch: алгоритмы и логика", "Scratch: algorithms and logic"),
      L("Python asoslari", "Основы Python", "Python fundamentals"),
      L("OOP va modullar", "ООП и модули", "OOP and modules"),
      L("SQL va PostgreSQL", "SQL и PostgreSQL", "SQL and PostgreSQL"),
      L("Django: modellar, view'lar, shablonlar", "Django: модели, представления, шаблоны", "Django: models, views, templates"),
      L("Django REST va deploy", "Django REST и деплой", "Django REST and deployment"),
    ],
    outcomes: [
      L("Ishlaydigan Django veb-ilova", "Рабочее веб-приложение на Django", "A working Django web app"),
      L("Ma’lumotlar bazasini loyihalay olasiz", "Умеете проектировать базы данных", "Design databases"),
      L("Junior backend intervyusiga tayyorsiz", "Готовы к собеседованию на junior backend", "Ready for junior backend interviews"),
    ],
  },
  {
    id: "3",
    slug: "frontend-development",
    category: "programming",
    title: L("Web dasturlash kursi (Frontend)", "Веб-разработка (Frontend)", "Web Development (Frontend)"),
    summary: L(
      "HTML, CSS, JavaScript va React bilan real loyihalar yaratish.",
      "Создание реальных проектов на HTML, CSS, JavaScript и React.",
      "Build real projects with HTML, CSS, JavaScript and React.",
    ),
    description: L(
      "Veb-sahifa tuzilishidan zamonaviy React ilovalarigacha. Har modul loyiha bilan tugaydi, kod mentor tomonidan tekshiriladi, Git va jamoaviy ish odatlari birinchi haftadan boshlanadi.",
      "От структуры веб-страницы до современных React-приложений. Каждый модуль заканчивается проектом, код проверяет ментор, Git и командная работа — с первой недели.",
      "From web page structure to modern React apps. Every module ends with a project, a mentor reviews your code, and Git and teamwork habits start in week one.",
    ),
    durationMonths: 8,
    lessonsPerWeek: 3,
    level: "beginner",
    format: "offline",
    branchIds: ["tashkent", "andijan"],
    modules: [
      L("HTML va semantik belgilash", "HTML и семантическая разметка", "HTML and semantic markup"),
      L("CSS, Flexbox, Grid va moslashuvchan dizayn", "CSS, Flexbox, Grid и адаптивная вёрстка", "CSS, Flexbox, Grid and responsive layout"),
      L("JavaScript asoslari va DOM", "Основы JavaScript и DOM", "JavaScript fundamentals and the DOM"),
      L("Asinxron JavaScript va API", "Асинхронный JavaScript и API", "Async JavaScript and APIs"),
      L("Git va GitHub", "Git и GitHub", "Git and GitHub"),
      L("React: komponentlar, holat, marshrutlash", "React: компоненты, состояние, маршрутизация", "React: components, state, routing"),
      L("Diplom loyihasi", "Дипломный проект", "Capstone project"),
    ],
    outcomes: [
      L("GitHub'da 5+ loyiha", "5+ проектов на GitHub", "5+ projects on GitHub"),
      L("Junior frontend intervyusiga tayyorsiz", "Готовы к собеседованию на junior frontend", "Ready for junior frontend interviews"),
      L("Jamoada Git bilan ishlay olasiz", "Умеете работать с Git в команде", "Work with Git in a team"),
    ],
  },
  {
    id: "7",
    slug: "mobile-development-flutter",
    category: "programming",
    title: L("Mobil dasturlash kursi (Flutter, Dart)", "Мобильная разработка (Flutter, Dart)", "Mobile Development (Flutter, Dart)"),
    summary: L(
      "Bitta kod bilan Android va iOS uchun ilovalar yaratish.",
      "Приложения для Android и iOS на одном коде.",
      "Apps for Android and iOS from a single codebase.",
    ),
    description: L(
      "Dart tilini o‘rganib, Flutter'da chiroyli va tez ishlaydigan mobil ilovalar yasaysiz: ekranlar, navigatsiya, API bilan ishlash, ma’lumotni saqlash va do‘konga chiqarish.",
      "Изучаете Dart и делаете в Flutter красивые и быстрые мобильные приложения: экраны, навигация, работа с API, хранение данных и публикация в магазине.",
      "Learn Dart and build fast, good-looking mobile apps in Flutter: screens, navigation, APIs, local storage and publishing to the store.",
    ),
    durationMonths: 7,
    lessonsPerWeek: 3,
    level: "intermediate",
    format: "offline",
    branchIds: ["tashkent"],
    modules: [
      L("Dart asoslari", "Основы Dart", "Dart fundamentals"),
      L("Flutter vidjetlari va maketlar", "Виджеты и макеты Flutter", "Flutter widgets and layouts"),
      L("Navigatsiya va holatni boshqarish", "Навигация и управление состоянием", "Navigation and state management"),
      L("REST API va Firebase", "REST API и Firebase", "REST APIs and Firebase"),
      L("Ilovani Google Play'ga chiqarish", "Публикация в Google Play", "Publishing to Google Play"),
    ],
    outcomes: [
      L("Do‘konga chiqarilgan ilova", "Приложение, опубликованное в магазине", "An app published to the store"),
      L("Android va iOS uchun bitta kod", "Один код для Android и iOS", "One codebase for Android and iOS"),
      L("Junior Flutter lavozimiga tayyorsiz", "Готовы к позиции junior Flutter", "Ready for a junior Flutter role"),
    ],
  },
  {
    id: "5",
    slug: "graphic-design",
    category: "design",
    title: L("Grafik dizayn (Graphic Design)", "Графический дизайн", "Graphic Design"),
    summary: L(
      "Ijodiy va texnologik ko‘nikmalarni rivojlantiruvchi dastur.",
      "Программа, развивающая творческие и технические навыки.",
      "A program that builds creative and technical skills together.",
    ),
    description: L(
      "Kompozitsiya, rang va tipografiyadan boshlab brend identifikatsiyasigacha. Figma va Adobe dasturlarida real buyurtmalarga o‘xshash topshiriqlar bajarib, kurs oxirida portfolio yig‘asiz.",
      "От композиции, цвета и типографики до айдентики бренда. Выполняете задания, похожие на реальные заказы, в Figma и программах Adobe и собираете портфолио.",
      "From composition, color and typography to brand identity. You work on client-style briefs in Figma and Adobe tools and finish with a portfolio.",
    ),
    durationMonths: 5,
    lessonsPerWeek: 3,
    level: "beginner",
    format: "hybrid",
    branchIds: ["tashkent", "samarkand"],
    modules: [
      L("Kompozitsiya va rang nazariyasi", "Композиция и теория цвета", "Composition and color theory"),
      L("Tipografiya", "Типографика", "Typography"),
      L("Adobe Photoshop va Illustrator", "Adobe Photoshop и Illustrator", "Adobe Photoshop and Illustrator"),
      L("Figma va ijtimoiy tarmoq dizayni", "Figma и дизайн для соцсетей", "Figma and social media design"),
      L("Logotip va brend identifikatsiyasi", "Логотип и айдентика бренда", "Logo and brand identity"),
      L("Portfolio va buyurtmachi bilan ishlash", "Портфолио и работа с заказчиком", "Portfolio and working with clients"),
    ],
    outcomes: [
      L("6–8 ishdan iborat portfolio", "Портфолио из 6–8 работ", "A portfolio of 6–8 pieces"),
      L("Brend uchun to‘liq vizual uslub", "Полный визуальный стиль бренда", "A complete visual style for a brand"),
      L("Frilans buyurtmalarga tayyorsiz", "Готовы к фриланс-заказам", "Ready for freelance orders"),
    ],
  },
  {
    id: "9",
    slug: "robotics",
    category: "robotics",
    title: L("Robototexnika", "Робототехника", "Robotics"),
    summary: L(
      "Arduino, sensorlar va motorlar bilan harakatlanadigan robotlar yasash.",
      "Собираем движущихся роботов на Arduino с датчиками и моторами.",
      "Build moving robots with Arduino, sensors and motors.",
    ),
    description: L(
      "Elektronika asoslaridan boshlab, Arduino'ni dasturlash, sensorlarni ulash va robotni boshqarishni o‘rganasiz. Har bir mavzu qo‘lda yig‘iladigan loyiha bilan mustahkamlanadi, kurs musobaqaga tayyorgarlik bilan yakunlanadi.",
      "Начиная с основ электроники, учитесь программировать Arduino, подключать датчики и управлять роботом. Каждая тема закрепляется проектом, который собирается руками, курс завершается подготовкой к соревнованиям.",
      "Starting from electronics basics, learn to program Arduino, wire sensors and control a robot. Every topic ends with a hands-on build, and the course closes with competition prep.",
    ),
    durationMonths: 6,
    lessonsPerWeek: 2,
    level: "beginner",
    format: "offline",
    branchIds: ["tashkent", "samarkand"],
    modules: [
      L("Elektronika asoslari", "Основы электроники", "Electronics basics"),
      L("Arduino'ni dasturlash", "Программирование Arduino", "Programming Arduino"),
      L("Sensorlar va motorlar", "Датчики и моторы", "Sensors and motors"),
      L("Chiziq bo‘ylab yuruvchi robot", "Робот, следующий по линии", "Line-following robot"),
      L("Musobaqa loyihasi", "Соревновательный проект", "Competition project"),
    ],
    outcomes: [
      L("O‘zingiz yig‘gan ishlaydigan robot", "Собственный работающий робот", "A working robot you built yourself"),
      L("Arduino'da mustaqil dasturlaysiz", "Самостоятельно программируете Arduino", "Program Arduino on your own"),
      L("Robototexnika musobaqalariga tayyorsiz", "Готовы к соревнованиям по робототехнике", "Ready for robotics competitions"),
    ],
  },
  {
    id: "8",
    slug: "3d-printing",
    category: "robotics",
    title: L("3D Printer kursi", "Курс 3D-печати", "3D Printing"),
    summary: L(
      "G‘oyadan tayyor buyumgacha: 3D modellashtirish va bosib chiqarish.",
      "От идеи до готовой вещи: 3D-моделирование и печать.",
      "From idea to finished object: 3D modeling and printing.",
    ),
    description: L(
      "Tinkercad va Fusion 360'da model chizishni, uni printerga tayyorlashni va bosib chiqarishni o‘rganasiz. Printerni sozlash, materiallar va xatolarni tuzatish amalda ko‘rsatiladi.",
      "Учитесь моделировать в Tinkercad и Fusion 360, готовить модель к печати и печатать. Настройку принтера, материалы и исправление ошибок разбираем на практике.",
      "Learn to model in Tinkercad and Fusion 360, prepare the model for printing and print it. Printer setup, materials and fixing failed prints are covered hands-on.",
    ),
    durationMonths: 3,
    lessonsPerWeek: 2,
    level: "beginner",
    format: "offline",
    branchIds: ["tashkent"],
    modules: [
      L("3D printer qanday ishlaydi", "Как работает 3D-принтер", "How a 3D printer works"),
      L("Tinkercad'da modellashtirish", "Моделирование в Tinkercad", "Modeling in Tinkercad"),
      L("Fusion 360 asoslari", "Основы Fusion 360", "Fusion 360 basics"),
      L("Slicer va printerni sozlash", "Слайсер и настройка принтера", "Slicers and printer setup"),
      L("Yakuniy buyum", "Итоговое изделие", "Final object"),
    ],
    outcomes: [
      L("O‘zingiz loyihalab chop etgan buyum", "Изделие, которое вы спроектировали и напечатали", "An object you designed and printed"),
      L("Printerni mustaqil sozlaysiz", "Самостоятельно настраиваете принтер", "Set up a printer on your own"),
      L("Model tayyorlash ko‘nikmasi", "Навык подготовки моделей", "Model preparation skills"),
    ],
  },
  {
    id: "6",
    slug: "english-a1-b2",
    category: "languages",
    title: L("Ingliz tili kursi (A1 dan B2 darajagacha)", "Английский язык (от A1 до B2)", "English (A1 to B2)"),
    summary: L(
      "Noldan B2 darajagacha: gapirish, tinglash, o‘qish va yozish.",
      "С нуля до B2: говорение, аудирование, чтение и письмо.",
      "From zero to B2: speaking, listening, reading and writing.",
    ),
    description: L(
      "Darajangizga qarab guruhga qo‘shilasiz va A1 dan B2 gacha bosqichma-bosqich o‘sasiz. Har bosqich oxirida test bor. IT sohasi uchun zarur so‘zlar va hujjatlarni o‘qish alohida mashq qilinadi.",
      "Вы попадаете в группу по своему уровню и шаг за шагом растёте от A1 до B2. В конце каждого уровня — тест. Отдельно тренируем лексику и чтение документации для IT.",
      "Join a group at your level and grow step by step from A1 to B2, with a test at the end of each level. IT vocabulary and reading technical docs get extra practice.",
    ),
    durationMonths: 12,
    lessonsPerWeek: 3,
    level: "beginner",
    format: "hybrid",
    branchIds: ALL,
    modules: [
      L("A1: boshlang‘ich", "A1: начальный", "A1: beginner"),
      L("A2: elementar", "A2: элементарный", "A2: elementary"),
      L("B1: o‘rta", "B1: средний", "B1: intermediate"),
      L("B2: o‘rtadan yuqori", "B2: выше среднего", "B2: upper-intermediate"),
      L("IT uchun ingliz tili", "Английский для IT", "English for IT"),
    ],
    outcomes: [
      L("B2 darajasida erkin muloqot", "Свободное общение на уровне B2", "Fluent conversation at B2"),
      L("Texnik hujjatlarni o‘qiy olasiz", "Читаете техническую документацию", "Read technical documentation"),
      L("Xalqaro imtihonga tayyorgarlik asosi", "Основа для международного экзамена", "A base for international exams"),
    ],
  },
  {
    id: "4",
    slug: "computer-literacy",
    category: "office",
    title: L("Kompyuter savodxonligi kursi", "Компьютерная грамотность", "Computer Literacy"),
    summary: L(
      "Kompyuter, Office dasturlari va internetdan ishonchli foydalanish.",
      "Уверенная работа с компьютером, программами Office и интернетом.",
      "Confident work with a computer, Office apps and the internet.",
    ),
    description: L(
      "Kompyuter bilan endi tanishayotganlar va ishda tezroq ishlashni istaganlar uchun. Hujjat, jadval va taqdimot tayyorlashni, internet va pochtadan xavfsiz foydalanishni amaliy topshiriqlar orqali o‘rganasiz.",
      "Для тех, кто только знакомится с компьютером или хочет работать быстрее. На практике учитесь готовить документы, таблицы и презентации, безопасно пользоваться интернетом и почтой.",
      "For people new to computers or anyone who wants to work faster. Through practice you learn to prepare documents, spreadsheets and presentations, and to use the internet and email safely.",
    ),
    durationMonths: 2,
    lessonsPerWeek: 3,
    level: "beginner",
    format: "offline",
    branchIds: ALL,
    modules: [
      L("Kompyuter va operatsion tizim asoslari", "Основы компьютера и операционной системы", "Computer and OS basics"),
      L("Word: hujjatlar", "Word: документы", "Word: documents"),
      L("Excel: jadval va formulalar", "Excel: таблицы и формулы", "Excel: tables and formulas"),
      L("PowerPoint: taqdimotlar", "PowerPoint: презентации", "PowerPoint: presentations"),
      L("Internet, pochta va raqamli xavfsizlik", "Интернет, почта и цифровая безопасность", "Internet, email and digital safety"),
    ],
    outcomes: [
      L("Ish hujjatlarini mustaqil tayyorlaysiz", "Самостоятельно готовите рабочие документы", "Prepare work documents on your own"),
      L("Excel'da hisob-kitob qilasiz", "Считаете в Excel", "Do calculations in Excel"),
      L("Onlayn xizmatlardan xavfsiz foydalanasiz", "Безопасно пользуетесь онлайн-сервисами", "Use online services safely"),
    ],
  },
];
